<?php

namespace Database\Seeders;

use App\Models\Course;
use App\Models\Exam;
use Illuminate\Database\Seeder;

class ExamSeeder extends Seeder
{
    public function run(): void
    {
        $examData = [
            'belajar-laravel-dari-nol' => [
                ['q' => 'Apa kepanjangan dari MVC dalam Laravel?', 'o' => ['Model View Controller', 'Module View Component', 'Main View Class', 'Master Visual Code'], 'a' => 1],
                ['q' => 'Perintah artisan untuk membuat controller baru adalah?', 'o' => ['php artisan make:controller', 'php artisan create:controller', 'php artisan new:controller', 'php artisan generate:controller'], 'a' => 1],
                ['q' => 'File konfigurasi database Laravel ada di?', 'o' => ['config/database.php', 'app/database.php', '.env saja', 'config/db.php'], 'a' => 1],
                ['q' => 'Method Eloquent untuk mengambil semua data adalah?', 'o' => ['Model::all()', 'Model::get()', 'Model::fetch()', 'Model::select()'], 'a' => 1],
                ['q' => 'Apa fungsi middleware di Laravel?', 'o' => ['Menyaring request HTTP', 'Mengelola database', 'Membuat view', 'Mengatur routing'], 'a' => 1],
                ['q' => 'Perintah untuk menjalankan migration adalah?', 'o' => ['php artisan migrate', 'php artisan db:migrate', 'php artisan run:migration', 'php artisan migration:run'], 'a' => 1],
                ['q' => 'Blade directive untuk menampilkan kondisi adalah?', 'o' => ['@if', '#if', '{{if}}', '<?if?>'], 'a' => 1],
                ['q' => 'Relasi one-to-many di Eloquent menggunakan method?', 'o' => ['hasMany()', 'belongsTo()', 'hasOne()', 'manyToMany()'], 'a' => 1],
                ['q' => 'File .env digunakan untuk?', 'o' => ['Konfigurasi environment', 'Routing aplikasi', 'Template view', 'Definisi model'], 'a' => 1],
                ['q' => 'Perintah artisan untuk membuat model adalah?', 'o' => ['php artisan make:model', 'php artisan create:model', 'php artisan new:model', 'php artisan model:create'], 'a' => 1],
                ['q' => 'Folder untuk menyimpan view di Laravel adalah?', 'o' => ['resources/views', 'app/views', 'public/views', 'storage/views'], 'a' => 1],
                ['q' => 'Apa itu seeder di Laravel?', 'o' => ['Pengisi data awal database', 'Pengaturan routing', 'Template email', 'Cache management'], 'a' => 1],
                ['q' => 'Method untuk redirect ke route lain adalah?', 'o' => ['redirect()->route()', 'goto()->route()', 'move()->route()', 'jump()->route()'], 'a' => 1],
                ['q' => 'Perintah untuk rollback migration adalah?', 'o' => ['php artisan migrate:rollback', 'php artisan migrate:undo', 'php artisan migrate:back', 'php artisan rollback:migrate'], 'a' => 1],
                ['q' => 'Cara mengambil data dengan kondisi di Eloquent?', 'o' => ['Model::where()', 'Model::find()', 'Model::filter()', 'Model::condition()'], 'a' => 1],
                ['q' => 'Apa fungsi Route::group() di Laravel?', 'o' => ['Mengelompokkan route dengan atribut sama', 'Membuat route baru', 'Menghapus route', 'Menduplikasi route'], 'a' => 1],
                ['q' => 'Perintah untuk membuat migration adalah?', 'o' => ['php artisan make:migration', 'php artisan create:migration', 'php artisan new:migration', 'php artisan migration:make'], 'a' => 1],
                ['q' => 'Storage facade digunakan untuk?', 'o' => ['Manajemen file/upload', 'Koneksi database', 'Session management', 'Cache storage'], 'a' => 1],
                ['q' => 'Cara menjalankan seeder tertentu adalah?', 'o' => ['php artisan db:seed --class=NamaSeeder', 'php artisan seed:run NamaSeeder', 'php artisan run:seeder NamaSeeder', 'php artisan seeder:run NamaSeeder'], 'a' => 1],
                ['q' => 'Eloquent method untuk menyimpan data baru adalah?', 'o' => ['create() atau save()', 'insert()', 'add()', 'store()'], 'a' => 1],
            ],
            'react-js-untuk-pemula' => [
                ['q' => 'JSX adalah singkatan dari?', 'o' => ['JavaScript XML', 'Java Syntax Extension', 'JavaScript Extra', 'Java XML Syntax'], 'a' => 1],
                ['q' => 'Hook untuk mengelola state di React adalah?', 'o' => ['useState', 'useData', 'useStore', 'useVariable'], 'a' => 1],
                ['q' => 'Cara merender list di React menggunakan?', 'o' => ['map()', 'forEach()', 'for loop', 'while loop'], 'a' => 1],
                ['q' => 'Props digunakan untuk?', 'o' => ['Mengirim data antar komponen', 'Mengelola state lokal', 'Fetch data API', 'Mengatur routing'], 'a' => 1],
                ['q' => 'useEffect digunakan untuk?', 'o' => ['Side effects seperti fetch data', 'Membuat state baru', 'Mengatur style', 'Membuat komponen'], 'a' => 1],
                ['q' => 'Komponen fungsional di React menggunakan?', 'o' => ['Function biasa atau arrow function', 'Class saja', 'Object saja', 'Interface saja'], 'a' => 1],
                ['q' => 'Key prop pada list digunakan untuk?', 'o' => ['Identifikasi unik tiap item', 'Styling item', 'Event handling', 'Data binding'], 'a' => 1],
                ['q' => 'React Router digunakan untuk?', 'o' => ['Navigasi halaman di SPA', 'Fetch data', 'State management', 'Styling komponen'], 'a' => 1],
                ['q' => 'Context API digunakan untuk?', 'o' => ['State management global', 'Routing', 'Animasi', 'Form handling'], 'a' => 1],
                ['q' => 'Virtual DOM berfungsi untuk?', 'o' => ['Meningkatkan performa render', 'Menyimpan data', 'Mengatur routing', 'Fetch API'], 'a' => 1],
                ['q' => 'Cara update state dengan benar adalah?', 'o' => ['Menggunakan setter dari useState', 'Langsung modifikasi state', 'Menggunakan this.state', 'Menggunakan var baru'], 'a' => 1],
                ['q' => 'Conditional rendering di React menggunakan?', 'o' => ['Ternary operator atau &&', 'if di luar JSX saja', 'switch saja', 'Semua sama'], 'a' => 1],
                ['q' => 'Event onClick di React ditulis sebagai?', 'o' => ['onClick={handler}', 'onclick="handler()"', 'on-click={handler}', 'click={handler}'], 'a' => 1],
                ['q' => 'useCallback digunakan untuk?', 'o' => ['Memoize fungsi agar tidak re-create', 'Membuat state', 'Fetch data', 'Routing'], 'a' => 1],
                ['q' => 'Perbedaan state dan props adalah?', 'o' => ['State lokal, props dari parent', 'Keduanya sama', 'Props lokal, state dari parent', 'Tidak ada perbedaan'], 'a' => 1],
                ['q' => 'React.Fragment digunakan untuk?', 'o' => ['Wrap elemen tanpa tambahan DOM', 'Membuat komponen baru', 'Fetch data', 'Routing'], 'a' => 1],
                ['q' => 'Library untuk HTTP request yang populer di React adalah?', 'o' => ['Axios', 'jQuery', 'Request', 'HTTP'], 'a' => 1],
                ['q' => 'useMemo digunakan untuk?', 'o' => ['Memoize nilai kalkulasi berat', 'Membuat state', 'Event handling', 'Routing'], 'a' => 1],
                ['q' => 'Cara import komponen di React adalah?', 'o' => ["import Komponen from './Komponen'", "require('./Komponen')", "include('./Komponen')", "load('./Komponen')"], 'a' => 1],
                ['q' => 'StrictMode di React berfungsi untuk?', 'o' => ['Mendeteksi masalah potensial', 'Mengunci state', 'Mematikan fitur tertentu', 'Optimasi produksi'], 'a' => 1],
            ],
            'flutter-complete-course' => [
                ['q' => 'Bahasa pemrograman yang digunakan Flutter adalah?', 'o' => ['Dart', 'Kotlin', 'Swift', 'Java'], 'a' => 1],
                ['q' => 'Widget dasar untuk menampilkan teks di Flutter adalah?', 'o' => ['Text', 'Label', 'Paragraph', 'TextView'], 'a' => 1],
                ['q' => 'StatefulWidget digunakan ketika?', 'o' => ['UI perlu berubah secara dinamis', 'UI statis saja', 'Tidak ada interaksi user', 'Hanya tampilan teks'], 'a' => 1],
                ['q' => 'Widget untuk layout horizontal di Flutter adalah?', 'o' => ['Row', 'Column', 'Stack', 'Flex'], 'a' => 1],
                ['q' => 'Navigator.push() digunakan untuk?', 'o' => ['Berpindah ke halaman baru', 'Kembali ke halaman sebelumnya', 'Menutup aplikasi', 'Refresh halaman'], 'a' => 1],
                ['q' => 'Package untuk HTTP request di Flutter adalah?', 'o' => ['http', 'axios', 'fetch', 'request'], 'a' => 1],
                ['q' => 'setState() digunakan untuk?', 'o' => ['Memperbarui UI setelah perubahan data', 'Mengambil data dari API', 'Navigasi halaman', 'Mengatur theme'], 'a' => 1],
                ['q' => 'Widget Scaffold menyediakan?', 'o' => ['Struktur halaman dasar (AppBar, Body)', 'Koneksi database', 'HTTP client', 'State management'], 'a' => 1],
                ['q' => 'pubspec.yaml digunakan untuk?', 'o' => ['Konfigurasi project dan dependencies', 'Routing aplikasi', 'Konfigurasi database', 'Styling widget'], 'a' => 1],
                ['q' => 'Async/await di Dart digunakan untuk?', 'o' => ['Operasi asinkron seperti API call', 'Loop biasa', 'Kondisi', 'Import library'], 'a' => 1],
                ['q' => 'Provider package digunakan untuk?', 'o' => ['State management', 'HTTP request', 'Database lokal', 'Navigasi'], 'a' => 1],
                ['q' => 'Widget Container berfungsi untuk?', 'o' => ['Box model: padding, margin, decoration', 'Teks saja', 'Gambar saja', 'Navigasi'], 'a' => 1],
                ['q' => 'FutureBuilder digunakan untuk?', 'o' => ['Render UI berdasarkan hasil Future/async', 'Loop widget', 'Animasi', 'Routing'], 'a' => 1],
                ['q' => 'SharedPreferences digunakan untuk?', 'o' => ['Menyimpan data sederhana lokal', 'Database relasional', 'HTTP request', 'Push notification'], 'a' => 1],
                ['q' => 'Hot reload di Flutter berguna untuk?', 'o' => ['Melihat perubahan kode tanpa restart', 'Deploy aplikasi', 'Testing', 'Build release'], 'a' => 1],
                ['q' => 'ListView.builder digunakan untuk?', 'o' => ['Render list panjang secara efisien', 'Menampilkan satu item', 'Grid layout', 'Tab layout'], 'a' => 1],
                ['q' => 'GestureDetector digunakan untuk?', 'o' => ['Mendeteksi gesture user (tap, swipe)', 'Animasi', 'Routing', 'State management'], 'a' => 1],
                ['q' => 'Perintah untuk build APK Flutter adalah?', 'o' => ['flutter build apk', 'flutter compile apk', 'flutter create apk', 'flutter export apk'], 'a' => 1],
                ['q' => 'StreamBuilder digunakan untuk?', 'o' => ['Render UI berdasarkan data Stream realtime', 'HTTP request sekali', 'Local storage', 'Routing'], 'a' => 1],
                ['q' => 'ThemeData digunakan untuk?', 'o' => ['Mengatur tema global aplikasi', 'Routing', 'Database', 'Push notification'], 'a' => 1],
            ],
            'python-untuk-data-science' => [
                ['q' => 'Library Python untuk manipulasi data tabular adalah?', 'o' => ['Pandas', 'NumPy', 'Matplotlib', 'Scikit-learn'], 'a' => 1],
                ['q' => 'Struktur data utama di Pandas adalah?', 'o' => ['DataFrame dan Series', 'List dan Tuple', 'Dict dan Set', 'Array dan Matrix'], 'a' => 1],
                ['q' => 'Cara membaca file CSV di Pandas?', 'o' => ['pd.read_csv()', 'pd.load_csv()', 'pd.open_csv()', 'pd.import_csv()'], 'a' => 1],
                ['q' => 'Library untuk visualisasi data dasar di Python?', 'o' => ['Matplotlib', 'Pandas', 'NumPy', 'SciPy'], 'a' => 1],
                ['q' => 'Fungsi untuk melihat info ringkas DataFrame?', 'o' => ['df.info()', 'df.summary()', 'df.describe()', 'df.details()'], 'a' => 1],
                ['q' => 'Cara menghapus baris duplikat di Pandas?', 'o' => ['df.drop_duplicates()', 'df.remove_duplicates()', 'df.delete_duplicates()', 'df.clean_duplicates()'], 'a' => 1],
                ['q' => 'NaN di Pandas merepresentasikan?', 'o' => ['Nilai yang hilang/kosong', 'Angka nol', 'String kosong', 'Nilai negatif'], 'a' => 1],
                ['q' => 'Fungsi NumPy untuk membuat array adalah?', 'o' => ['np.array()', 'np.create()', 'np.new()', 'np.make()'], 'a' => 1],
                ['q' => 'groupby() di Pandas digunakan untuk?', 'o' => ['Agregasi data berdasarkan kolom', 'Sorting data', 'Filter data', 'Menggabungkan DataFrame'], 'a' => 1],
                ['q' => 'Cara menggabungkan dua DataFrame secara horizontal?', 'o' => ['pd.merge() atau join()', 'pd.concat() axis=0', 'pd.append()', 'pd.combine()'], 'a' => 1],
                ['q' => 'Seaborn dibangun di atas library?', 'o' => ['Matplotlib', 'Pandas', 'NumPy', 'Plotly'], 'a' => 1],
                ['q' => 'Cara filter baris di DataFrame dengan kondisi?', 'o' => ['df[df["col"] > nilai]', 'df.filter("col > nilai")', 'df.where("col > nilai")', 'df.select("col > nilai")'], 'a' => 1],
                ['q' => 'Fungsi untuk statistik deskriptif DataFrame?', 'o' => ['df.describe()', 'df.stats()', 'df.summary()', 'df.report()'], 'a' => 1],
                ['q' => 'Cara mengganti nilai NaN dengan 0?', 'o' => ['df.fillna(0)', 'df.replace_nan(0)', 'df.fill(0)', 'df.nan_to(0)'], 'a' => 1],
                ['q' => 'pivot_table() di Pandas digunakan untuk?', 'o' => ['Membuat tabel ringkasan agregasi', 'Join dua tabel', 'Filter data', 'Sort data'], 'a' => 1],
                ['q' => 'Library untuk visualisasi interaktif di Python?', 'o' => ['Plotly', 'Matplotlib', 'Seaborn', 'Bokeh saja'], 'a' => 1],
                ['q' => 'Cara memilih kolom tertentu dari DataFrame?', 'o' => ['df["nama_kolom"] atau df[["col1","col2"]]', 'df.select("nama_kolom")', 'df.get("nama_kolom")', 'df.column("nama_kolom")'], 'a' => 1],
                ['q' => 'apply() di Pandas digunakan untuk?', 'o' => ['Menerapkan fungsi ke setiap baris/kolom', 'Filter data', 'Sort data', 'Merge data'], 'a' => 1],
                ['q' => 'Cara melihat 5 baris pertama DataFrame?', 'o' => ['df.head()', 'df.first()', 'df.top()', 'df.start()'], 'a' => 1],
                ['q' => 'Correlation matrix dibuat dengan fungsi?', 'o' => ['df.corr()', 'df.correlation()', 'df.matrix()', 'df.relation()'], 'a' => 1],
            ],
            'machine-learning-dengan-python' => [
                ['q' => 'Library Machine Learning utama di Python adalah?', 'o' => ['Scikit-learn', 'Pandas', 'NumPy', 'Matplotlib'], 'a' => 1],
                ['q' => 'Supervised learning membutuhkan?', 'o' => ['Data berlabel (fitur + target)', 'Data tanpa label', 'Hanya fitur saja', 'Hanya target saja'], 'a' => 1],
                ['q' => 'Algoritma untuk masalah klasifikasi adalah?', 'o' => ['Logistic Regression', 'Linear Regression', 'K-Means', 'PCA'], 'a' => 1],
                ['q' => 'Overfitting terjadi ketika?', 'o' => ['Model terlalu hafal data training', 'Model tidak belajar sama sekali', 'Data terlalu sedikit', 'Fitur terlalu banyak'], 'a' => 1],
                ['q' => 'Train-test split digunakan untuk?', 'o' => ['Evaluasi model pada data baru', 'Membersihkan data', 'Visualisasi data', 'Feature engineering'], 'a' => 1],
                ['q' => 'Metrik evaluasi untuk klasifikasi adalah?', 'o' => ['Accuracy, Precision, Recall, F1', 'MSE, RMSE, MAE', 'R-squared', 'Silhouette Score'], 'a' => 1],
                ['q' => 'K-Means termasuk jenis algoritma?', 'o' => ['Unsupervised learning', 'Supervised learning', 'Reinforcement learning', 'Semi-supervised'], 'a' => 1],
                ['q' => 'Feature scaling dilakukan menggunakan?', 'o' => ['StandardScaler atau MinMaxScaler', 'Hanya normalisasi manual', 'Tidak perlu scaling', 'Hanya log transform'], 'a' => 1],
                ['q' => 'Random Forest adalah kumpulan dari?', 'o' => ['Banyak Decision Tree', 'Banyak Neural Network', 'Banyak SVM', 'Banyak KNN'], 'a' => 1],
                ['q' => 'Cross-validation digunakan untuk?', 'o' => ['Evaluasi model yang lebih robust', 'Training model lebih cepat', 'Membersihkan data', 'Visualisasi hasil'], 'a' => 1],
                ['q' => 'Hyperparameter tuning menggunakan?', 'o' => ['GridSearchCV atau RandomizedSearchCV', 'Hanya trial and error manual', 'Selalu default', 'Tidak diperlukan'], 'a' => 1],
                ['q' => 'Confusion matrix menampilkan?', 'o' => ['TP, FP, TN, FN dari prediksi', 'Akurasi saja', 'Loss saja', 'Distribusi data'], 'a' => 1],
                ['q' => 'Linear Regression memprediksi?', 'o' => ['Nilai kontinu (regresi)', 'Kelas/label (klasifikasi)', 'Cluster', 'Anomali'], 'a' => 1],
                ['q' => 'Principal Component Analysis (PCA) digunakan untuk?', 'o' => ['Reduksi dimensi fitur', 'Klasifikasi', 'Regresi', 'Clustering'], 'a' => 1],
                ['q' => 'Underfitting terjadi ketika?', 'o' => ['Model terlalu sederhana untuk data', 'Model terlalu kompleks', 'Data terlalu banyak', 'Fitur terlalu sedikit'], 'a' => 1],
                ['q' => 'Gradient descent digunakan untuk?', 'o' => ['Optimasi parameter model', 'Cleaning data', 'Visualisasi', 'Split data'], 'a' => 1],
                ['q' => 'KNN (K-Nearest Neighbor) memprediksi berdasarkan?', 'o' => ['K tetangga terdekat', 'Semua data training', 'Rata-rata global', 'Median data'], 'a' => 1],
                ['q' => 'Regularisasi L1 disebut juga?', 'o' => ['Lasso Regression', 'Ridge Regression', 'Elastic Net', 'Dropout'], 'a' => 1],
                ['q' => 'ROC-AUC digunakan untuk evaluasi?', 'o' => ['Model klasifikasi', 'Model regresi', 'Clustering', 'Reduksi dimensi'], 'a' => 1],
                ['q' => 'Pipeline di Scikit-learn digunakan untuk?', 'o' => ['Menggabungkan preprocessing + model', 'Visualisasi saja', 'Split data saja', 'Import data'], 'a' => 1],
            ],
            'ui-ux-design-dengan-figma' => [
                ['q' => 'UX adalah singkatan dari?', 'o' => ['User Experience', 'User Extension', 'Unified Experience', 'User Execution'], 'a' => 1],
                ['q' => 'UI adalah singkatan dari?', 'o' => ['User Interface', 'User Integration', 'Unified Interface', 'User Interaction'], 'a' => 1],
                ['q' => 'Wireframe digunakan untuk?', 'o' => ['Kerangka awal desain tanpa detail visual', 'Desain final berwarna', 'Prototype interaktif', 'Handoff ke developer'], 'a' => 1],
                ['q' => 'Color theory warna komplementer adalah?', 'o' => ['Warna berlawanan di color wheel', 'Warna yang mirip', 'Warna monokromatik', 'Warna hangat saja'], 'a' => 1],
                ['q' => 'Grid system digunakan untuk?', 'o' => ['Konsistensi tata letak elemen', 'Warna desain', 'Typography', 'Iconografi'], 'a' => 1],
                ['q' => 'Prototype di Figma digunakan untuk?', 'o' => ['Simulasi interaksi dan flow aplikasi', 'Ekspor aset', 'Coding frontend', 'Database design'], 'a' => 1],
                ['q' => 'Design System adalah?', 'o' => ['Kumpulan komponen dan aturan desain', 'Alat desain saja', 'Framework CSS', 'Library icon'], 'a' => 1],
                ['q' => 'Typography yang baik memperhatikan?', 'o' => ['Font, ukuran, spasi, dan hierarki', 'Hanya font saja', 'Hanya warna teks', 'Hanya ukuran saja'], 'a' => 1],
                ['q' => 'User flow digunakan untuk?', 'o' => ['Memetakan perjalanan user dalam aplikasi', 'Desain warna', 'Pemilihan font', 'Coding'], 'a' => 1],
                ['q' => 'Accessibility dalam desain berarti?', 'o' => ['Dapat digunakan semua orang termasuk disabilitas', 'Desain yang cantik', 'Desain yang cepat load', 'Desain yang murah'], 'a' => 1],
                ['q' => 'Auto layout di Figma berfungsi untuk?', 'o' => ['Layout responsif dan fleksibel', 'Ekspor gambar', 'Membuat animasi', 'Menambah warna'], 'a' => 1],
                ['q' => 'Component di Figma digunakan untuk?', 'o' => ['Reusable element yang konsisten', 'Sekali pakai saja', 'Animasi saja', 'Export aset'], 'a' => 1],
                ['q' => 'Contrast ratio minimal untuk teks yang accessible adalah?', 'o' => ['4.5:1 (WCAG AA)', '2:1', '8:1', '1:1'], 'a' => 1],
                ['q' => 'Negative space (white space) dalam desain berguna untuk?', 'o' => ['Meningkatkan keterbacaan dan fokus', 'Menghemat ruang', 'Memperbanyak konten', 'Tidak berguna'], 'a' => 1],
                ['q' => 'Heuristic evaluation adalah?', 'o' => ['Evaluasi usability berdasarkan prinsip desain', 'Testing dengan user asli', 'A/B testing', 'Analytics data'], 'a' => 1],
                ['q' => 'Persona dalam UX adalah?', 'o' => ['Representasi fiktif pengguna target', 'Data analytics real', 'Profil developer', 'Nama produk'], 'a' => 1],
                ['q' => 'F-pattern dan Z-pattern berkaitan dengan?', 'o' => ['Pola baca mata pengguna', 'Layout grid', 'Typography', 'Color scheme'], 'a' => 1],
                ['q' => 'Handoff design ke developer menggunakan fitur Figma?', 'o' => ['Inspect panel / Dev Mode', 'Prototype mode', 'Component panel', 'Layer panel'], 'a' => 1],
                ['q' => 'Iterative design berarti?', 'o' => ['Desain terus diperbaiki berdasarkan feedback', 'Desain dibuat sekali jadi', 'Desain tanpa testing', 'Desain cepat selesai'], 'a' => 1],
                ['q' => 'Call to Action (CTA) dalam desain UI adalah?', 'o' => ['Elemen yang mendorong user melakukan aksi', 'Judul halaman', 'Footer website', 'Navigasi menu'], 'a' => 1],
            ],
            'docker-kubernetes-fundamentals' => [
                ['q' => 'Docker Image adalah?', 'o' => ['Template read-only untuk container', 'Container yang sedang berjalan', 'File konfigurasi', 'Volume data'], 'a' => 1],
                ['q' => 'Perintah untuk menjalankan container Docker adalah?', 'o' => ['docker run', 'docker start', 'docker exec', 'docker up'], 'a' => 1],
                ['q' => 'Dockerfile digunakan untuk?', 'o' => ['Mendefinisikan instruksi build image', 'Menjalankan container', 'Konfigurasi jaringan', 'Manajemen volume'], 'a' => 1],
                ['q' => 'Docker Compose digunakan untuk?', 'o' => ['Mengelola multi-container aplikasi', 'Build single image', 'Push image ke registry', 'Monitor container'], 'a' => 1],
                ['q' => 'Kubernetes Pod adalah?', 'o' => ['Unit terkecil deployment di K8s', 'Cluster K8s', 'Node worker', 'Service K8s'], 'a' => 1],
                ['q' => 'Perintah untuk melihat semua pod di Kubernetes?', 'o' => ['kubectl get pods', 'kubectl list pods', 'kubectl show pods', 'kubectl view pods'], 'a' => 1],
                ['q' => 'Kubernetes Service digunakan untuk?', 'o' => ['Expose pod ke jaringan', 'Deploy aplikasi', 'Scaling pod', 'Monitor cluster'], 'a' => 1],
                ['q' => 'Docker Volume digunakan untuk?', 'o' => ['Persistensi data container', 'Komunikasi container', 'Build image', 'Expose port'], 'a' => 1],
                ['q' => 'Kubernetes Deployment mengelola?', 'o' => ['Replika pod dan rolling update', 'Jaringan cluster', 'Storage persistent', 'Konfigurasi secret'], 'a' => 1],
                ['q' => 'ENV di Dockerfile digunakan untuk?', 'o' => ['Mendefinisikan environment variable', 'Copy file', 'Expose port', 'Run command'], 'a' => 1],
                ['q' => 'Docker Registry adalah?', 'o' => ['Tempat menyimpan dan distribusi image', 'Container runtime', 'Orchestration tool', 'Monitoring tool'], 'a' => 1],
                ['q' => 'ConfigMap di Kubernetes digunakan untuk?', 'o' => ['Konfigurasi non-sensitif aplikasi', 'Data sensitif seperti password', 'Routing traffic', 'Scaling pod'], 'a' => 1],
                ['q' => 'Kubernetes Secret digunakan untuk?', 'o' => ['Menyimpan data sensitif (password, token)', 'Konfigurasi biasa', 'Log aplikasi', 'Monitoring'], 'a' => 1],
                ['q' => 'Horizontal Pod Autoscaler (HPA) berfungsi untuk?', 'o' => ['Auto scaling pod berdasarkan beban', 'Deploy manual', 'Backup data', 'Load balancing manual'], 'a' => 1],
                ['q' => 'docker build digunakan untuk?', 'o' => ['Build image dari Dockerfile', 'Menjalankan container', 'Push ke registry', 'Pull image'], 'a' => 1],
                ['q' => 'Ingress di Kubernetes digunakan untuk?', 'o' => ['Routing HTTP/HTTPS ke service', 'Internal communication', 'Volume management', 'Secret management'], 'a' => 1],
                ['q' => 'Container berbeda dengan VM karena?', 'o' => ['Container berbagi kernel OS host', 'Container lebih lambat', 'Container butuh OS penuh', 'Container tidak portable'], 'a' => 1],
                ['q' => 'Perintah untuk masuk ke dalam container adalah?', 'o' => ['docker exec -it container bash', 'docker enter container', 'docker login container', 'docker ssh container'], 'a' => 1],
                ['q' => 'Namespace di Kubernetes digunakan untuk?', 'o' => ['Isolasi resource antar tim/environment', 'Networking', 'Storage', 'Monitoring'], 'a' => 1],
                ['q' => 'Rolling update di Kubernetes memastikan?', 'o' => ['Zero downtime deployment', 'Deployment lebih cepat', 'Lebih sedikit resource', 'Tidak perlu testing'], 'a' => 1],
            ],
            'ethical-hacking-penetration-testing' => [
                ['q' => 'Ethical hacking dilakukan dengan?', 'o' => ['Izin tertulis dari pemilik sistem', 'Tanpa izin siapapun', 'Izin verbal saja', 'Tidak perlu izin'], 'a' => 1],
                ['q' => 'Penetration testing phase pertama adalah?', 'o' => ['Reconnaissance (pengumpulan informasi)', 'Exploitation', 'Reporting', 'Scanning'], 'a' => 1],
                ['q' => 'Tools untuk network scanning yang populer?', 'o' => ['Nmap', 'Wireshark', 'Metasploit', 'Burp Suite'], 'a' => 1],
                ['q' => 'SQL Injection menyerang komponen apa?', 'o' => ['Database melalui input yang tidak divalidasi', 'Server langsung', 'Jaringan', 'File sistem'], 'a' => 1],
                ['q' => 'XSS (Cross-Site Scripting) digunakan untuk?', 'o' => ['Injeksi script berbahaya ke browser korban', 'Serangan database', 'Brute force password', 'Sniffing jaringan'], 'a' => 1],
                ['q' => 'Metasploit Framework digunakan untuk?', 'o' => ['Eksploitasi vulnerability', 'Scanning jaringan saja', 'Monitoring traffic', 'Enkripsi data'], 'a' => 1],
                ['q' => 'Social engineering menyerang?', 'o' => ['Faktor manusia/psikologi', 'Sistem teknis', 'Database', 'Jaringan'], 'a' => 1],
                ['q' => 'Brute force attack adalah?', 'o' => ['Mencoba semua kemungkinan kombinasi password', 'Menyerang fisik server', 'Menyadap komunikasi', 'Menyuntik kode berbahaya'], 'a' => 1],
                ['q' => 'Wireshark digunakan untuk?', 'o' => ['Analisis paket jaringan', 'Scanning port', 'Eksploitasi vulnerability', 'Password cracking'], 'a' => 1],
                ['q' => 'CVE adalah singkatan dari?', 'o' => ['Common Vulnerabilities and Exposures', 'Critical Virus Exposure', 'Cyber Vulnerability Engine', 'Common Virus Entry'], 'a' => 1],
                ['q' => 'OWASP Top 10 adalah daftar?', 'o' => ['Kerentanan keamanan web paling kritis', 'Tools hacking terbaik', 'Framework keamanan', 'Sertifikasi keamanan'], 'a' => 1],
                ['q' => 'Privilege escalation berarti?', 'o' => ['Mendapatkan hak akses lebih tinggi', 'Menurunkan hak akses', 'Login sebagai user biasa', 'Membuat akun baru'], 'a' => 1],
                ['q' => 'Burp Suite digunakan untuk?', 'o' => ['Testing keamanan aplikasi web', 'Network scanning', 'Password cracking', 'Malware analysis'], 'a' => 1],
                ['q' => 'Phishing adalah teknik?', 'o' => ['Penipuan untuk mencuri kredensial', 'Serangan jaringan teknis', 'Eksploitasi kode', 'Enkripsi data'], 'a' => 1],
                ['q' => 'CSRF (Cross-Site Request Forgery) menyerang?', 'o' => ['Aksi tidak sah atas nama user yang login', 'Database', 'Server langsung', 'File sistem'], 'a' => 1],
                ['q' => 'Penetration test report harus berisi?', 'o' => ['Temuan, risiko, dan rekomendasi perbaikan', 'Hanya daftar tools yang digunakan', 'Hanya screenshot saja', 'Hanya waktu pengerjaan'], 'a' => 1],
                ['q' => 'Zero-day vulnerability adalah?', 'o' => ['Kerentanan yang belum ada patch-nya', 'Bug yang sudah dipatch', 'Kerentanan lama', 'Kerentanan tidak berbahaya'], 'a' => 1],
                ['q' => 'DMZ (Demilitarized Zone) dalam jaringan adalah?', 'o' => ['Segmen jaringan antara internet dan internal', 'Area tanpa firewall', 'Zona tanpa monitoring', 'Jaringan private'], 'a' => 1],
                ['q' => 'Password hashing yang aman menggunakan?', 'o' => ['bcrypt atau Argon2', 'MD5', 'SHA1', 'Base64'], 'a' => 1],
                ['q' => 'Responsible disclosure berarti?', 'o' => ['Melaporkan vulnerability ke vendor sebelum publik', 'Langsung publish ke publik', 'Menjual vulnerability', 'Mengeksploitasi untuk keuntungan'], 'a' => 1],
            ],
            'aws-cloud-practitioner' => [
                ['q' => 'AWS adalah singkatan dari?', 'o' => ['Amazon Web Services', 'Advanced Web System', 'Automated Web Service', 'Amazon World Service'], 'a' => 1],
                ['q' => 'AWS Region adalah?', 'o' => ['Lokasi geografis cluster data center AWS', 'Satu data center saja', 'Jaringan global AWS', 'Zona ketersediaan tunggal'], 'a' => 1],
                ['q' => 'Amazon EC2 adalah layanan untuk?', 'o' => ['Virtual machine di cloud', 'Object storage', 'Database managed', 'DNS service'], 'a' => 1],
                ['q' => 'Amazon S3 digunakan untuk?', 'o' => ['Object storage yang scalable', 'Virtual machine', 'Database relasional', 'Serverless function'], 'a' => 1],
                ['q' => 'IAM di AWS digunakan untuk?', 'o' => ['Manajemen identitas dan akses', 'Monitoring resource', 'Load balancing', 'DNS management'], 'a' => 1],
                ['q' => 'Amazon RDS adalah layanan?', 'o' => ['Database relasional managed', 'NoSQL database', 'Cache database', 'Object storage'], 'a' => 1],
                ['q' => 'AWS Lambda adalah layanan?', 'o' => ['Serverless compute (run code tanpa server)', 'Virtual machine', 'Container service', 'Database service'], 'a' => 1],
                ['q' => 'Availability Zone (AZ) adalah?', 'o' => ['Data center terisolasi dalam satu Region', 'Seluruh Region AWS', 'Edge location', 'Jaringan CDN'], 'a' => 1],
                ['q' => 'CloudWatch di AWS digunakan untuk?', 'o' => ['Monitoring dan observability resource', 'Storage data', 'Compute service', 'Networking'], 'a' => 1],
                ['q' => 'Model pricing AWS yang bayar sesuai pemakaian?', 'o' => ['Pay-as-you-go', 'Fixed monthly fee', 'Annual license', 'Per device fee'], 'a' => 1],
                ['q' => 'Amazon VPC digunakan untuk?', 'o' => ['Jaringan virtual private di AWS', 'Object storage', 'Compute service', 'Database service'], 'a' => 1],
                ['q' => 'AWS Shared Responsibility Model berarti?', 'o' => ['AWS dan customer berbagi tanggung jawab keamanan', 'AWS bertanggung jawab penuh', 'Customer bertanggung jawab penuh', 'Tidak ada tanggung jawab'], 'a' => 1],
                ['q' => 'Auto Scaling di AWS digunakan untuk?', 'o' => ['Menambah/kurangi kapasitas otomatis', 'Monitoring biaya', 'Backup data', 'DNS management'], 'a' => 1],
                ['q' => 'Elastic Load Balancer (ELB) berfungsi untuk?', 'o' => ['Distribusi traffic ke beberapa instance', 'Penyimpanan data', 'Database caching', 'Serverless function'], 'a' => 1],
                ['q' => 'Amazon CloudFront adalah layanan?', 'o' => ['CDN (Content Delivery Network)', 'Database', 'Virtual machine', 'Serverless'], 'a' => 1],
                ['q' => 'AWS Well-Architected Framework memiliki berapa pilar?', 'o' => ['6 pilar', '3 pilar', '4 pilar', '5 pilar'], 'a' => 1],
                ['q' => 'Amazon DynamoDB adalah database jenis?', 'o' => ['NoSQL managed', 'Relasional managed', 'In-memory cache', 'Time-series'], 'a' => 1],
                ['q' => 'AWS Free Tier memberikan akses gratis selama?', 'o' => ['12 bulan untuk layanan tertentu', '6 bulan semua layanan', '1 bulan penuh', 'Selamanya semua layanan'], 'a' => 1],
                ['q' => 'Amazon Route 53 adalah layanan?', 'o' => ['DNS dan routing traffic', 'Object storage', 'Compute service', 'Database service'], 'a' => 1],
                ['q' => 'AWS CLI digunakan untuk?', 'o' => ['Manage layanan AWS via command line', 'Monitoring visual', 'Billing management saja', 'Support ticket'], 'a' => 1],
            ],
            'unity-game-development-2d' => [
                ['q' => 'Unity menggunakan bahasa pemrograman?', 'o' => ['C#', 'Java', 'Python', 'C++'], 'a' => 1],
                ['q' => 'GameObject di Unity adalah?', 'o' => ['Objek dasar di scene Unity', 'Script C#', 'File gambar', 'Audio clip'], 'a' => 1],
                ['q' => 'Rigidbody2D digunakan untuk?', 'o' => ['Simulasi fisika pada objek 2D', 'Render sprite', 'Audio playback', 'Input handling'], 'a' => 1],
                ['q' => 'Collider2D digunakan untuk?', 'o' => ['Deteksi tabrakan antar objek', 'Animasi sprite', 'Pergerakan kamera', 'Spawn objek'], 'a' => 1],
                ['q' => 'Method Update() di Unity dipanggil?', 'o' => ['Setiap frame', 'Sekali saat start', 'Setiap detik', 'Saat collision'], 'a' => 1],
                ['q' => 'Prefab di Unity adalah?', 'o' => ['Template objek yang bisa di-reuse', 'Script utama game', 'Folder asset', 'Scene baru'], 'a' => 1],
                ['q' => 'Animator Controller digunakan untuk?', 'o' => ['Mengatur state machine animasi', 'Physics objek', 'Audio manager', 'Scene loading'], 'a' => 1],
                ['q' => 'Time.deltaTime digunakan untuk?', 'o' => ['Pergerakan konsisten di semua frame rate', 'Mengatur waktu in-game', 'Timer countdown', 'Delay function'], 'a' => 1],
                ['q' => 'Canvas di Unity digunakan untuk?', 'o' => ['UI element (text, button, image)', 'Background scene', 'Tile map', 'Physics layer'], 'a' => 1],
                ['q' => 'PlayerPrefs digunakan untuk?', 'o' => ['Menyimpan data sederhana lokal (skor, setting)', 'Networking', 'Physics', 'Animation'], 'a' => 1],
                ['q' => 'SceneManager.LoadScene() digunakan untuk?', 'o' => ['Berpindah atau load scene baru', 'Spawn objek', 'Play audio', 'Pause game'], 'a' => 1],
                ['q' => 'Tilemap digunakan untuk?', 'o' => ['Membuat level dari tile 2D', 'UI design', 'Animasi karakter', 'Audio management'], 'a' => 1],
                ['q' => 'OnCollisionEnter2D dipanggil ketika?', 'o' => ['Dua objek dengan Rigidbody bertabrakan', 'Objek dihancurkan', 'Scene di-load', 'Game di-pause'], 'a' => 1],
                ['q' => 'AudioSource.Play() digunakan untuk?', 'o' => ['Memutar audio clip', 'Animasi karakter', 'Physics simulation', 'UI update'], 'a' => 1],
                ['q' => 'Camera.main mengacu pada?', 'o' => ['Kamera utama yang bertag "MainCamera"', 'Semua kamera di scene', 'Kamera pertama dibuat', 'Kamera UI'], 'a' => 1],
                ['q' => 'Coroutine di Unity digunakan untuk?', 'o' => ['Eksekusi kode dengan delay/async', 'Physics calculation', 'Render pipeline', 'Audio mixing'], 'a' => 1],
                ['q' => 'Layer di Unity digunakan untuk?', 'o' => ['Kategorisasi objek untuk physics/rendering', 'Animasi', 'Audio', 'Scripting'], 'a' => 1],
                ['q' => 'Build Settings di Unity digunakan untuk?', 'o' => ['Konfigurasi platform target export', 'Debug script', 'Asset management', 'Physics setting'], 'a' => 1],
                ['q' => 'Singleton pattern di Unity biasa digunakan untuk?', 'o' => ['GameManager yang persisten antar scene', 'Animasi', 'Physics', 'UI update'], 'a' => 1],
                ['q' => 'Instantiate() di Unity digunakan untuk?', 'o' => ['Membuat instance objek/prefab baru di scene', 'Menghapus objek', 'Load scene', 'Play audio'], 'a' => 1],
            ],
            'digital-marketing-masterclass' => [
                ['q' => 'SEO adalah singkatan dari?', 'o' => ['Search Engine Optimization', 'Social Engine Optimization', 'Search Email Optimization', 'Site Engine Operation'], 'a' => 1],
                ['q' => 'CTR adalah singkatan dari?', 'o' => ['Click-Through Rate', 'Cost To Reach', 'Content Transfer Rate', 'Customer Traffic Rate'], 'a' => 1],
                ['q' => 'Google Analytics digunakan untuk?', 'o' => ['Analisis traffic dan perilaku pengunjung website', 'Membuat iklan', 'SEO on-page', 'Email marketing'], 'a' => 1],
                ['q' => 'Backlink dalam SEO adalah?', 'o' => ['Link dari website lain ke website kita', 'Link internal di website kita', 'Anchor text', 'Meta description'], 'a' => 1],
                ['q' => 'Bounce rate yang tinggi berarti?', 'o' => ['Pengunjung langsung keluar tanpa interaksi', 'Banyak halaman dikunjungi', 'Konversi tinggi', 'Loading cepat'], 'a' => 1],
                ['q' => 'CPC adalah singkatan dari?', 'o' => ['Cost Per Click', 'Content Per Click', 'Customer Per Campaign', 'Cost Per Conversion'], 'a' => 1],
                ['q' => 'Email marketing yang efektif memiliki?', 'o' => ['Subject menarik, konten relevan, CTA jelas', 'Hanya gambar besar', 'Email teks panjang saja', 'Tidak perlu CTA'], 'a' => 1],
                ['q' => 'ROI dalam marketing adalah?', 'o' => ['Return on Investment', 'Rate of Impressions', 'Reach of Interest', 'Revenue of Impact'], 'a' => 1],
                ['q' => 'A/B testing digunakan untuk?', 'o' => ['Membandingkan dua versi untuk optimasi', 'Testing website speed', 'Security testing', 'Database testing'], 'a' => 1],
                ['q' => 'Retargeting/remarketing menyasar?', 'o' => ['Pengunjung yang sudah pernah ke website', 'Pengguna baru saja', 'Semua pengguna internet', 'Pengguna kompetitor'], 'a' => 1],
                ['q' => 'Meta description di SEO berfungsi untuk?', 'o' => ['Deskripsi halaman di hasil pencarian', 'Judul halaman', 'Konten utama', 'Alt text gambar'], 'a' => 1],
                ['q' => 'Keyword research dilakukan untuk?', 'o' => ['Menemukan kata kunci yang dicari target audiens', 'Desain website', 'Membuat iklan berbayar saja', 'Email marketing saja'], 'a' => 1],
                ['q' => 'Social proof dalam marketing adalah?', 'o' => ['Testimoni, review, rating dari pelanggan', 'Logo brand', 'Harga produk', 'Deskripsi produk'], 'a' => 1],
                ['q' => 'Funnel pemasaran terdiri dari tahap?', 'o' => ['Awareness, Consideration, Conversion', 'Hanya Awareness', 'Hanya Conversion', 'Conversion, Awareness, Consideration'], 'a' => 1],
                ['q' => 'Organic traffic berasal dari?', 'o' => ['Hasil pencarian non-berbayar (SEO)', 'Iklan berbayar', 'Social media ads', 'Email campaign'], 'a' => 1],
                ['q' => 'Engagement rate di social media mengukur?', 'o' => ['Interaksi (like, comment, share) per impression', 'Jumlah follower saja', 'Jumlah posting', 'Jangkauan saja'], 'a' => 1],
                ['q' => 'Landing page yang baik harus memiliki?', 'o' => ['Satu CTA yang jelas dan fokus', 'Banyak menu navigasi', 'Banyak gambar tanpa teks', 'Link ke banyak halaman'], 'a' => 1],
                ['q' => 'Content marketing bertujuan untuk?', 'o' => ['Menarik dan mempertahankan audiens dengan konten bernilai', 'Iklan langsung produk saja', 'Spam email', 'Hanya posting di media sosial'], 'a' => 1],
                ['q' => 'CPM adalah singkatan dari?', 'o' => ['Cost Per Mille (per 1000 impression)', 'Cost Per Month', 'Click Per Message', 'Cost Per Member'], 'a' => 1],
                ['q' => 'UTM parameter digunakan untuk?', 'o' => ['Tracking sumber traffic di Google Analytics', 'Optimasi SEO', 'Email template', 'Desain landing page'], 'a' => 1],
            ],
            'nodejs-express-rest-api' => [
                ['q' => 'Node.js adalah?', 'o' => ['Runtime JavaScript di server-side', 'Framework JavaScript', 'Database JavaScript', 'Browser JavaScript'], 'a' => 1],
                ['q' => 'Express.js digunakan untuk?', 'o' => ['Framework web minimalis untuk Node.js', 'Database ORM', 'Template engine', 'Testing framework'], 'a' => 1],
                ['q' => 'npm adalah singkatan dari?', 'o' => ['Node Package Manager', 'Node Project Manager', 'New Package Module', 'Node Program Module'], 'a' => 1],
                ['q' => 'Middleware di Express digunakan untuk?', 'o' => ['Memproses request sebelum sampai route handler', 'Membuat database', 'Template rendering', 'File management'], 'a' => 1],
                ['q' => 'HTTP method untuk membuat data baru di REST API?', 'o' => ['POST', 'GET', 'PUT', 'DELETE'], 'a' => 1],
                ['q' => 'HTTP status code 404 berarti?', 'o' => ['Resource tidak ditemukan', 'Server error', 'Sukses', 'Unauthorized'], 'a' => 1],
                ['q' => 'JWT adalah singkatan dari?', 'o' => ['JSON Web Token', 'JavaScript Web Type', 'JSON World Transfer', 'JavaScript Widget Token'], 'a' => 1],
                ['q' => 'Mongoose digunakan untuk?', 'o' => ['ODM untuk MongoDB di Node.js', 'ORM untuk MySQL', 'HTTP client', 'Testing tool'], 'a' => 1],
                ['q' => 'REST API menggunakan format data?', 'o' => ['JSON atau XML (umumnya JSON)', 'Hanya XML', 'Binary saja', 'CSV saja'], 'a' => 1],
                ['q' => 'async/await di Node.js digunakan untuk?', 'o' => ['Mengelola operasi asinkron lebih bersih', 'Membuat loop', 'Deklarasi variabel', 'Import module'], 'a' => 1],
                ['q' => 'HTTP status code 200 berarti?', 'o' => ['Request berhasil', 'Not found', 'Server error', 'Unauthorized'], 'a' => 1],
                ['q' => 'CORS di Express digunakan untuk?', 'o' => ['Mengizinkan request dari origin berbeda', 'Authentication', 'Database connection', 'File upload'], 'a' => 1],
                ['q' => 'bcrypt digunakan untuk?', 'o' => ['Hashing password', 'Enkripsi data biasa', 'JWT signing', 'Database query'], 'a' => 1],
                ['q' => 'req.body di Express berisi?', 'o' => ['Data yang dikirim di request body (POST/PUT)', 'Query string', 'Route parameter', 'Header request'], 'a' => 1],
                ['q' => 'package.json berisi?', 'o' => ['Metadata project dan daftar dependencies', 'Kode utama aplikasi', 'Konfigurasi database', 'Template HTML'], 'a' => 1],
                ['q' => 'HTTP method untuk menghapus data di REST API?', 'o' => ['DELETE', 'POST', 'GET', 'PATCH'], 'a' => 1],
                ['q' => 'Environment variable di Node.js diakses via?', 'o' => ['process.env.NAMA_VAR', 'env.NAMA_VAR', 'config.NAMA_VAR', 'system.NAMA_VAR'], 'a' => 1],
                ['q' => 'Multer di Express digunakan untuk?', 'o' => ['Handle file upload', 'Authentication', 'Database query', 'Email sending'], 'a' => 1],
                ['q' => 'HTTP status code 401 berarti?', 'o' => ['Unauthorized (belum autentikasi)', 'Forbidden', 'Not found', 'Server error'], 'a' => 1],
                ['q' => 'Rate limiting di API digunakan untuk?', 'o' => ['Membatasi jumlah request per waktu', 'Mempercepat API', 'Kompresi data', 'Caching'], 'a' => 1],
            ],
        ];

        $courses = Course::all()->keyBy('slug');

        foreach ($courses as $slug => $course) {
            $questions = $examData[$slug] ?? [];

            if (empty($questions)) continue;

            foreach ($questions as $index => $item) {
                $soalNumber = $index + 1;

                Exam::firstOrCreate(
                    [
                        'course_id' => $course->id,
                        'soal'      => $soalNumber,
                    ],
                    [
                        'question'       => $item['q'],
                        'option1'        => $item['o'][0],
                        'option2'        => $item['o'][1],
                        'option3'        => $item['o'][2],
                        'option4'        => $item['o'][3],
                        'correct_answer' => $item['a'],
                        'pertama'        => $soalNumber === 1 ? 1 : 0,
                    ]
                );
            }
        }
    }
}
